FROM ubuntu:20.04
ENV DEBIAN_FRONTEND=noninteractive
RUN apt-get update && apt-get install -y --no-install-recommends \
    openssh-server python3 python3-apt python3-pip sudo curl vim gnupg lsb-release ca-certificates && \
    mkdir /var/run/sshd && useradd -ms /bin/bash ansible && echo 'ansible:ansible' | chpasswd && \
    usermod -aG sudo ansible && echo 'ansible ALL=(ALL) NOPASSWD:ALL' >> /etc/sudoers.d/ansible && \
    apt-get clean && rm -rf /var/lib/apt/lists/*
EXPOSE 22 80 3306 8404
CMD ["/usr/sbin/sshd","-D"]
